// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260415174821_AddUserBankDetailsFields")]
    partial class AddUserBankDetailsFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Attendance", b =>
                {
                    b.Property<Guid>("strAttendanceGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime?>("dtCheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dtCheckOut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dtCreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateOnly>("dtDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("dtUpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("strRemarks")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("strStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("strUserGUID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("strAttendanceGUID");

                    b.HasIndex("strUserGUID");

                    b.ToTable("Attendances", (string)null);
                });

            modelBuilder.Entity("Backend.Models.EmployeeShift", b =>
                {
                    b.Property<Guid>("strEmployeeShiftGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("dtCreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateOnly>("dtDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("dtUpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("strNotes")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("strShiftGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("strUserGUID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("strEmployeeShiftGUID");

                    b.HasIndex("strShiftGUID");

                    b.HasIndex("strUserGUID");

                    b.ToTable("EmployeeShifts", (string)null);
                });

            modelBuilder.Entity("Backend.Models.LeaveRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Days")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EmergencyContact")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LeaveType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("LeaveRecords");
                });

            modelBuilder.Entity("Backend.Models.Login", b =>
                {
                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("pass");

                    b.HasKey("Email");

                    b.ToTable("Login", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Menu", b =>
                {
                    b.Property<Guid>("strMenuGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("bolHasSubMenu")
                        .HasColumnType("bit");

                    b.Property<bool>("bolIsActive")
                        .HasColumnType("bit");

                    b.Property<double>("dblSeqNo")
                        .HasColumnType("float");

                    b.Property<DateTime>("dtCreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dtUpdateOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("strCreatedByGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("strIconName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strMapKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strMenuName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strMenuPositions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("strParentMenuGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("strPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("strUpdatedByGUID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("strMenuGUID");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("Backend.Models.PayrollCompliance", b =>
                {
                    b.Property<Guid>("strComplianceGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("bitIsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("decAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("dtCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dtDueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dtFiledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dtUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("strAuthority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strFilingReference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strPeriod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("strComplianceGUID");

                    b.ToTable("PayrollCompliances");
                });

            modelBuilder.Entity("Backend.Models.PayrollEmployee", b =>
                {
                    b.Property<Guid>("strPayrollEmployeeGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("bitIsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("decBaseSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("decGrossEarnings")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("decHRA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("decHealthInsurance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("decIncomeTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("decMedicalAllowance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("decNetPay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("decPerformanceBonus")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("decProvidentFund")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("decTotalDeductions")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("decTransportAllowance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("decYTDGross")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("decYTDTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("dtCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dtUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("strBankLast4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strBankName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strEmploymentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strPayPeriod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strTaxBracket")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("strUserGUID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("strPayrollEmployeeGUID");

                    b.HasIndex("strUserGUID");

                    b.ToTable("PayrollEmployees");
                });

            modelBuilder.Entity("Backend.Models.PayrollRun", b =>
                {
                    b.Property<Guid>("strPayrollRunGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("bitIsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("decTotalDeductions")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("decTotalGross")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("decTotalNetPay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("dtCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dtInitiatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dtPaidAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dtUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("intEmployeeCount")
                        .HasColumnType("int");

                    b.Property<Guid?>("strInitiatedByUserGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("strPayPeriod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strRunID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strStepsJSON")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("strPayrollRunGUID");

                    b.HasIndex("strInitiatedByUserGUID");

                    b.ToTable("PayrollRuns");
                });

            modelBuilder.Entity("Backend.Models.RecruitmentCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AppliedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("RecruitmentCandidates", (string)null);
                });

            modelBuilder.Entity("Backend.Models.RecruitmentJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ClosingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HiringManager")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("PostedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ResponsibilitiesCsv")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Salary")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("SkillsCsv")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.ToTable("RecruitmentJobs", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Register", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("FullName");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Password");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Registers", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Shift", b =>
                {
                    b.Property<Guid>("strShiftGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<bool>("bolIsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("dtCreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("dtUpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("strColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("strName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<TimeSpan>("tEndTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("tStartTime")
                        .HasColumnType("time");

                    b.HasKey("strShiftGUID");

                    b.ToTable("Shifts", (string)null);

                    b.HasData(
                        new
                        {
                            strShiftGUID = new Guid("e1a1a1a1-1111-1111-1111-111111111111"),
                            bolIsActive = true,
                            dtCreatedOn = new DateTime(2026, 4, 15, 17, 48, 20, 756, DateTimeKind.Utc).AddTicks(5260),
                            dtUpdatedOn = new DateTime(2026, 4, 15, 17, 48, 20, 756, DateTimeKind.Utc).AddTicks(5264),
                            strColor = "#fbbf24",
                            strName = "Morning Shift",
                            tEndTime = new TimeSpan(0, 16, 0, 0, 0),
                            tStartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            strShiftGUID = new Guid("e2a2a2a2-2222-2222-2222-222222222222"),
                            bolIsActive = true,
                            dtCreatedOn = new DateTime(2026, 4, 15, 17, 48, 20, 756, DateTimeKind.Utc).AddTicks(5302),
                            dtUpdatedOn = new DateTime(2026, 4, 15, 17, 48, 20, 756, DateTimeKind.Utc).AddTicks(5303),
                            strColor = "#3b82f6",
                            strName = "Afternoon Shift",
                            tEndTime = new TimeSpan(0, 0, 0, 0, 0),
                            tStartTime = new TimeSpan(0, 16, 0, 0, 0)
                        },
                        new
                        {
                            strShiftGUID = new Guid("e3a3a3a3-3333-3333-3333-333333333333"),
                            bolIsActive = true,
                            dtCreatedOn = new DateTime(2026, 4, 15, 17, 48, 20, 756, DateTimeKind.Utc).AddTicks(5310),
                            dtUpdatedOn = new DateTime(2026, 4, 15, 17, 48, 20, 756, DateTimeKind.Utc).AddTicks(5310),
                            strColor = "#8b5cf6",
                            strName = "Night Shift",
                            tEndTime = new TimeSpan(0, 8, 0, 0, 0),
                            tStartTime = new TimeSpan(0, 0, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Property<Guid>("strUserGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("bolIsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("bolSystemCreated")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("dDob")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dtCreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dtLastLogin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dtOTPExpiry")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dtRefreshTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dtUpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("strBankAccountNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strBankName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("strCreatedByGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("strEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strOTP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strPhoneNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strPreferredLanguage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strProfileImg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strRefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("strRoleGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("strTaxBracket")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("strUpdatedByGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("strUserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("strUserGUID");

                    b.HasIndex("strRoleGUID");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Backend.Models.UserRight", b =>
                {
                    b.Property<Guid>("strUserRightGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("bolCanApprove")
                        .HasColumnType("bit");

                    b.Property<bool>("bolCanDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("bolCanEdit")
                        .HasColumnType("bit");

                    b.Property<bool>("bolCanExport")
                        .HasColumnType("bit");

                    b.Property<bool>("bolCanImport")
                        .HasColumnType("bit");

                    b.Property<bool>("bolCanPrint")
                        .HasColumnType("bit");

                    b.Property<bool>("bolCanSave")
                        .HasColumnType("bit");

                    b.Property<bool>("bolCanView")
                        .HasColumnType("bit");

                    b.Property<DateTime>("dtCreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dtUpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("strCreatedByGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("strMenuGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("strUpdatedByGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("strUserRoleGUID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("strUserRightGUID");

                    b.ToTable("UserRights");
                });

            modelBuilder.Entity("Backend.Models.UserRole", b =>
                {
                    b.Property<Guid>("strUserRoleGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("bolIsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("bolSystemCreated")
                        .HasColumnType("bit");

                    b.Property<DateTime>("dtCreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dtUpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("strCreatedByGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("strDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strRoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("strUpdatedByGUID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("strUserRoleGUID");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            strUserRoleGUID = new Guid("22222222-2222-2222-2222-222222222222"),
                            bolIsActive = true,
                            bolSystemCreated = true,
                            dtCreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            dtUpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            strDesc = "Human Resources with management access",
                            strRoleName = "HR"
                        },
                        new
                        {
                            strUserRoleGUID = new Guid("33333333-3333-3333-3333-333333333333"),
                            bolIsActive = true,
                            bolSystemCreated = true,
                            dtCreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            dtUpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            strDesc = "Standard employee access",
                            strRoleName = "Employee"
                        });
                });

            modelBuilder.Entity("Backend.Models.Attendance", b =>
                {
                    b.HasOne("Backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("strUserGUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.EmployeeShift", b =>
                {
                    b.HasOne("Backend.Models.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("strShiftGUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("strUserGUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shift");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.PayrollEmployee", b =>
                {
                    b.HasOne("Backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("strUserGUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.PayrollRun", b =>
                {
                    b.HasOne("Backend.Models.User", "InitiatedByUser")
                        .WithMany()
                        .HasForeignKey("strInitiatedByUserGUID");

                    b.Navigation("InitiatedByUser");
                });

            modelBuilder.Entity("Backend.Models.RecruitmentCandidate", b =>
                {
                    b.HasOne("Backend.Models.RecruitmentJob", "Job")
                        .WithMany("Candidates")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.HasOne("Backend.Models.UserRole", "UserRole")
                        .WithMany()
                        .HasForeignKey("strRoleGUID");

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("Backend.Models.RecruitmentJob", b =>
                {
                    b.Navigation("Candidates");
                });
#pragma warning restore 612, 618
        }
    }
}
