// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260403190717_AddRecruitmentTables")]
    partial class AddRecruitmentTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Attendance", b =>
                {
                    b.Property<Guid>("strAttendanceGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime?>("dtCheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dtCheckOut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dtCreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateOnly>("dtDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("dtUpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("strRemarks")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("strStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("strUserGUID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("strAttendanceGUID");

                    b.HasIndex("strUserGUID");

                    b.ToTable("Attendances", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Blog", b =>
                {
                    b.Property<string>("strBlogGUID")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("strBlogGUID");

                    b.Property<string>("CategorystrCategoryGUID")
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool>("bolIsActive")
                        .HasColumnType("bit")
                        .HasColumnName("bolIsActive");

                    b.Property<bool>("bolIsFeatured")
                        .HasColumnType("bit")
                        .HasColumnName("bolIsFeatured");

                    b.Property<bool>("bolIsPublished")
                        .HasColumnType("bit")
                        .HasColumnName("bolIsPublished");

                    b.Property<DateTime>("dtCreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("dtCreatedOn");

                    b.Property<DateTime?>("dtPublishDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("dtPublishDate");

                    b.Property<DateTime?>("dtUpdatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("dtUpdatedOn");

                    b.Property<string>("strBlogSlug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("strBlogSlug");

                    b.Property<string>("strBlogTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("strBlogTitle");

                    b.Property<string>("strCategoryGUID")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("strCategoryGUID");

                    b.Property<string>("strCreatedByGUID")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("strCreatedByGUID");

                    b.Property<string>("strFeaturedImage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("strFeaturedImage");

                    b.Property<string>("strFullContent")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("strFullContent");

                    b.Property<string>("strMetaDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("strMetaDescription");

                    b.Property<string>("strMetaKeywords")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("strMetaKeywords");

                    b.Property<string>("strMetaTitle")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("strMetaTitle");

                    b.Property<string>("strShortDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("strShortDescription");

                    b.Property<string>("strUpdatedByGUID")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("strUpdatedByGUID");

                    b.HasKey("strBlogGUID");

                    b.HasIndex("CategorystrCategoryGUID");

                    b.ToTable("mstBlog");
                });

            modelBuilder.Entity("Backend.Models.BlogCategory", b =>
                {
                    b.Property<string>("strCategoryGUID")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("strCategoryGUID");

                    b.Property<bool>("bolIsActive")
                        .HasColumnType("bit")
                        .HasColumnName("bolIsActive");

                    b.Property<DateTime>("dtCreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("dtCreatedOn");

                    b.Property<DateTime?>("dtUpdatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("dtUpdatedOn");

                    b.Property<int>("intDisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("intDisplayOrder");

                    b.Property<string>("strCategoryDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("strCategoryDescription");

                    b.Property<string>("strCategoryImage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("strCategoryImage");

                    b.Property<string>("strCategoryName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("strCategoryName");

                    b.Property<string>("strCategorySlug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("strCategorySlug");

                    b.Property<string>("strCreatedByGUID")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("strCreatedByGUID");

                    b.Property<string>("strMetaDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("strMetaDescription");

                    b.Property<string>("strMetaKeywords")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("strMetaKeywords");

                    b.Property<string>("strMetaTitle")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("strMetaTitle");

                    b.Property<string>("strUpdatedByGUID")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("strUpdatedByGUID");

                    b.HasKey("strCategoryGUID");

                    b.ToTable("mstBlogCategory");
                });

            modelBuilder.Entity("Backend.Models.BlogTag", b =>
                {
                    b.Property<string>("strTagGUID")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("strTagGUID");

                    b.Property<bool>("bolIsActive")
                        .HasColumnType("bit")
                        .HasColumnName("bolIsActive");

                    b.Property<DateTime>("dtCreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("dtCreatedOn");

                    b.Property<DateTime?>("dtUpdatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("dtUpdatedOn");

                    b.Property<string>("strCreatedByGUID")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("strCreatedByGUID");

                    b.Property<string>("strTagName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("strTagName");

                    b.Property<string>("strTagSlug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("strTagSlug");

                    b.Property<string>("strUpdatedByGUID")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("strUpdatedByGUID");

                    b.HasKey("strTagGUID");

                    b.ToTable("mstBlogTag");
                });

            modelBuilder.Entity("Backend.Models.EmployeeShift", b =>
                {
                    b.Property<Guid>("strEmployeeShiftGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("dtCreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateOnly>("dtDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("dtUpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("strNotes")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("strShiftGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("strUserGUID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("strEmployeeShiftGUID");

                    b.HasIndex("strShiftGUID");

                    b.HasIndex("strUserGUID");

                    b.ToTable("EmployeeShifts", (string)null);
                });

            modelBuilder.Entity("Backend.Models.LeaveRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Days")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EmergencyContact")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LeaveType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("LeaveRecords");
                });

            modelBuilder.Entity("Backend.Models.Login", b =>
                {
                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("pass");

                    b.HasKey("Email");

                    b.ToTable("Login", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Menu", b =>
                {
                    b.Property<Guid>("strMenuGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("bolHasSubMenu")
                        .HasColumnType("bit");

                    b.Property<bool>("bolIsActive")
                        .HasColumnType("bit");

                    b.Property<double>("dblSeqNo")
                        .HasColumnType("float");

                    b.Property<DateTime>("dtCreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dtUpdateOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("strCreatedByGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("strIconName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strMapKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strMenuName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strMenuPositions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("strParentMenuGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("strPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("strUpdatedByGUID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("strMenuGUID");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("Backend.Models.RecruitmentCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AppliedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("RecruitmentCandidates", (string)null);
                });

            modelBuilder.Entity("Backend.Models.RecruitmentJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ClosingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HiringManager")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("PostedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ResponsibilitiesCsv")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Salary")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("SkillsCsv")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.ToTable("RecruitmentJobs", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Register", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("FullName");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Password");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Registers", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Shift", b =>
                {
                    b.Property<Guid>("strShiftGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<bool>("bolIsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("dtCreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("dtUpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("strColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("strName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<TimeSpan>("tEndTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("tStartTime")
                        .HasColumnType("time");

                    b.HasKey("strShiftGUID");

                    b.ToTable("Shifts", (string)null);

                    b.HasData(
                        new
                        {
                            strShiftGUID = new Guid("e1a1a1a1-1111-1111-1111-111111111111"),
                            bolIsActive = true,
                            dtCreatedOn = new DateTime(2026, 4, 3, 19, 7, 17, 354, DateTimeKind.Utc).AddTicks(174),
                            dtUpdatedOn = new DateTime(2026, 4, 3, 19, 7, 17, 354, DateTimeKind.Utc).AddTicks(179),
                            strColor = "#fbbf24",
                            strName = "Morning Shift",
                            tEndTime = new TimeSpan(0, 16, 0, 0, 0),
                            tStartTime = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            strShiftGUID = new Guid("e2a2a2a2-2222-2222-2222-222222222222"),
                            bolIsActive = true,
                            dtCreatedOn = new DateTime(2026, 4, 3, 19, 7, 17, 354, DateTimeKind.Utc).AddTicks(195),
                            dtUpdatedOn = new DateTime(2026, 4, 3, 19, 7, 17, 354, DateTimeKind.Utc).AddTicks(195),
                            strColor = "#3b82f6",
                            strName = "Afternoon Shift",
                            tEndTime = new TimeSpan(0, 0, 0, 0, 0),
                            tStartTime = new TimeSpan(0, 16, 0, 0, 0)
                        },
                        new
                        {
                            strShiftGUID = new Guid("e3a3a3a3-3333-3333-3333-333333333333"),
                            bolIsActive = true,
                            dtCreatedOn = new DateTime(2026, 4, 3, 19, 7, 17, 354, DateTimeKind.Utc).AddTicks(198),
                            dtUpdatedOn = new DateTime(2026, 4, 3, 19, 7, 17, 354, DateTimeKind.Utc).AddTicks(199),
                            strColor = "#8b5cf6",
                            strName = "Night Shift",
                            tEndTime = new TimeSpan(0, 8, 0, 0, 0),
                            tStartTime = new TimeSpan(0, 0, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Property<Guid>("strUserGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("bolIsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("bolSystemCreated")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("dDob")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dtCreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dtLastLogin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dtOTPExpiry")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dtRefreshTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dtUpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("strCreatedByGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("strEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strOTP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strPhoneNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strPreferredLanguage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strProfileImg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strRefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("strRoleGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("strUpdatedByGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("strUserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("strUserGUID");

                    b.HasIndex("strRoleGUID");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Backend.Models.UserRight", b =>
                {
                    b.Property<Guid>("strUserRightGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("bolCanApprove")
                        .HasColumnType("bit");

                    b.Property<bool>("bolCanDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("bolCanEdit")
                        .HasColumnType("bit");

                    b.Property<bool>("bolCanExport")
                        .HasColumnType("bit");

                    b.Property<bool>("bolCanImport")
                        .HasColumnType("bit");

                    b.Property<bool>("bolCanPrint")
                        .HasColumnType("bit");

                    b.Property<bool>("bolCanSave")
                        .HasColumnType("bit");

                    b.Property<bool>("bolCanView")
                        .HasColumnType("bit");

                    b.Property<DateTime>("dtCreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dtUpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("strCreatedByGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("strMenuGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("strUpdatedByGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("strUserRoleGUID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("strUserRightGUID");

                    b.ToTable("UserRights");
                });

            modelBuilder.Entity("Backend.Models.UserRole", b =>
                {
                    b.Property<Guid>("strUserRoleGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("bolIsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("bolSystemCreated")
                        .HasColumnType("bit");

                    b.Property<DateTime>("dtCreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dtUpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("strCreatedByGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("strDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strRoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("strUpdatedByGUID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("strUserRoleGUID");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            strUserRoleGUID = new Guid("11111111-1111-1111-1111-111111111111"),
                            bolIsActive = true,
                            bolSystemCreated = true,
                            dtCreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            dtUpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            strDesc = "System Administrator with full access",
                            strRoleName = "Super Admin"
                        },
                        new
                        {
                            strUserRoleGUID = new Guid("22222222-2222-2222-2222-222222222222"),
                            bolIsActive = true,
                            bolSystemCreated = true,
                            dtCreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            dtUpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            strDesc = "Human Resources with management access",
                            strRoleName = "HR"
                        },
                        new
                        {
                            strUserRoleGUID = new Guid("33333333-3333-3333-3333-333333333333"),
                            bolIsActive = true,
                            bolSystemCreated = true,
                            dtCreatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            dtUpdatedOn = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            strDesc = "Standard employee access",
                            strRoleName = "Employee"
                        });
                });

            modelBuilder.Entity("Backend.Models.Attendance", b =>
                {
                    b.HasOne("Backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("strUserGUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.Blog", b =>
                {
                    b.HasOne("Backend.Models.BlogCategory", "Category")
                        .WithMany("Blogs")
                        .HasForeignKey("CategorystrCategoryGUID");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Backend.Models.EmployeeShift", b =>
                {
                    b.HasOne("Backend.Models.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("strShiftGUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("strUserGUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shift");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.RecruitmentCandidate", b =>
                {
                    b.HasOne("Backend.Models.RecruitmentJob", "Job")
                        .WithMany("Candidates")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.HasOne("Backend.Models.UserRole", "UserRole")
                        .WithMany()
                        .HasForeignKey("strRoleGUID");

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("Backend.Models.BlogCategory", b =>
                {
                    b.Navigation("Blogs");
                });

            modelBuilder.Entity("Backend.Models.RecruitmentJob", b =>
                {
                    b.Navigation("Candidates");
                });
#pragma warning restore 612, 618
        }
    }
}
