// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Blog", b =>
                {
                    b.Property<string>("strBlogGUID")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("strBlogGUID");

                    b.Property<string>("CategorystrCategoryGUID")
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool>("bolIsActive")
                        .HasColumnType("bit")
                        .HasColumnName("bolIsActive");

                    b.Property<bool>("bolIsFeatured")
                        .HasColumnType("bit")
                        .HasColumnName("bolIsFeatured");

                    b.Property<bool>("bolIsPublished")
                        .HasColumnType("bit")
                        .HasColumnName("bolIsPublished");

                    b.Property<DateTime>("dtCreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("dtCreatedOn");

                    b.Property<DateTime?>("dtPublishDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("dtPublishDate");

                    b.Property<DateTime?>("dtUpdatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("dtUpdatedOn");

                    b.Property<string>("strBlogSlug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("strBlogSlug");

                    b.Property<string>("strBlogTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("strBlogTitle");

                    b.Property<string>("strCategoryGUID")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("strCategoryGUID");

                    b.Property<string>("strCreatedByGUID")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("strCreatedByGUID");

                    b.Property<string>("strFeaturedImage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("strFeaturedImage");

                    b.Property<string>("strFullContent")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("strFullContent");

                    b.Property<string>("strMetaDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("strMetaDescription");

                    b.Property<string>("strMetaKeywords")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("strMetaKeywords");

                    b.Property<string>("strMetaTitle")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("strMetaTitle");

                    b.Property<string>("strShortDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("strShortDescription");

                    b.Property<string>("strUpdatedByGUID")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("strUpdatedByGUID");

                    b.HasKey("strBlogGUID");

                    b.HasIndex("CategorystrCategoryGUID");

                    b.ToTable("mstBlog");
                });

            modelBuilder.Entity("Backend.Models.BlogCategory", b =>
                {
                    b.Property<string>("strCategoryGUID")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("strCategoryGUID");

                    b.Property<bool>("bolIsActive")
                        .HasColumnType("bit")
                        .HasColumnName("bolIsActive");

                    b.Property<DateTime>("dtCreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("dtCreatedOn");

                    b.Property<DateTime?>("dtUpdatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("dtUpdatedOn");

                    b.Property<int>("intDisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("intDisplayOrder");

                    b.Property<string>("strCategoryDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("strCategoryDescription");

                    b.Property<string>("strCategoryImage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("strCategoryImage");

                    b.Property<string>("strCategoryName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("strCategoryName");

                    b.Property<string>("strCategorySlug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("strCategorySlug");

                    b.Property<string>("strCreatedByGUID")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("strCreatedByGUID");

                    b.Property<string>("strMetaDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("strMetaDescription");

                    b.Property<string>("strMetaKeywords")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("strMetaKeywords");

                    b.Property<string>("strMetaTitle")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("strMetaTitle");

                    b.Property<string>("strUpdatedByGUID")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("strUpdatedByGUID");

                    b.HasKey("strCategoryGUID");

                    b.ToTable("mstBlogCategory");
                });

            modelBuilder.Entity("Backend.Models.BlogTag", b =>
                {
                    b.Property<string>("strTagGUID")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("strTagGUID");

                    b.Property<bool>("bolIsActive")
                        .HasColumnType("bit")
                        .HasColumnName("bolIsActive");

                    b.Property<DateTime>("dtCreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("dtCreatedOn");

                    b.Property<DateTime?>("dtUpdatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("dtUpdatedOn");

                    b.Property<string>("strCreatedByGUID")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("strCreatedByGUID");

                    b.Property<string>("strTagName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("strTagName");

                    b.Property<string>("strTagSlug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("strTagSlug");

                    b.Property<string>("strUpdatedByGUID")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("strUpdatedByGUID");

                    b.HasKey("strTagGUID");

                    b.ToTable("mstBlogTag");
                });

            modelBuilder.Entity("Backend.Models.Login", b =>
                {
                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("pass");

                    b.HasKey("Email");

                    b.ToTable("Login", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Menu", b =>
                {
                    b.Property<Guid>("strMenuGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("bolHasSubMenu")
                        .HasColumnType("bit");

                    b.Property<bool>("bolIsActive")
                        .HasColumnType("bit");

                    b.Property<double>("dblSeqNo")
                        .HasColumnType("float");

                    b.Property<DateTime>("dtCreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dtUpdateOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("strCreatedByGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("strIconName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strMapKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strMenuName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strMenuPositions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("strParentMenuGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("strPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("strUpdatedByGUID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("strMenuGUID");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("Backend.Models.Register", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("FullName");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Password");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Registers", (string)null);
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Property<Guid>("strUserGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("bolIsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("bolSystemCreated")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("dDob")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dtCreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dtLastLogin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dtOTPExpiry")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dtRefreshTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dtUpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("strCreatedByGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("strEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strOTP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strPhoneNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strPreferredLanguage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strProfileImg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strRefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("strRoleGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("strUpdatedByGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("strUserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("strUserGUID");

                    b.HasIndex("strRoleGUID");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Backend.Models.UserRight", b =>
                {
                    b.Property<Guid>("strUserRightGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("bolCanApprove")
                        .HasColumnType("bit");

                    b.Property<bool>("bolCanDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("bolCanEdit")
                        .HasColumnType("bit");

                    b.Property<bool>("bolCanExport")
                        .HasColumnType("bit");

                    b.Property<bool>("bolCanImport")
                        .HasColumnType("bit");

                    b.Property<bool>("bolCanPrint")
                        .HasColumnType("bit");

                    b.Property<bool>("bolCanSave")
                        .HasColumnType("bit");

                    b.Property<bool>("bolCanView")
                        .HasColumnType("bit");

                    b.Property<DateTime>("dtCreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dtUpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("strCreatedByGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("strMenuGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("strUpdatedByGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("strUserRoleGUID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("strUserRightGUID");

                    b.ToTable("UserRights");
                });

            modelBuilder.Entity("Backend.Models.UserRole", b =>
                {
                    b.Property<Guid>("strUserRoleGUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("bolIsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("bolSystemCreated")
                        .HasColumnType("bit");

                    b.Property<DateTime>("dtCreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dtUpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("strCreatedByGUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("strDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strRoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("strUpdatedByGUID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("strUserRoleGUID");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Backend.Models.Blog", b =>
                {
                    b.HasOne("Backend.Models.BlogCategory", "Category")
                        .WithMany("Blogs")
                        .HasForeignKey("CategorystrCategoryGUID");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.HasOne("Backend.Models.UserRole", "UserRole")
                        .WithMany()
                        .HasForeignKey("strRoleGUID");

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("Backend.Models.BlogCategory", b =>
                {
                    b.Navigation("Blogs");
                });
#pragma warning restore 612, 618
        }
    }
}
